# Generated by Django 5.1.4 on 2025-01-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_user_username_alter_user_role_article_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
