# Generated by Django 5.1.4 on 2025-01-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_article_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["created_at"]},
        ),
    ]
