# Generated by Django 5.1.4 on 2025-01-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_article_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["title"]},
        ),
    ]
